name: aws

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  deploy:
      needs: build
      name: Deploy
      runs-on: [ self-hosted, label-development ]

      steps:
        - name: Pull origin repository
          run: git pull origin develop

        - name: Docker rebuild
          run: docker-compose up --detach --build
